language: go

go:
  - "1.11.2"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev gcc
  - sudo apt-get install -y snapd
  - export PATH=/snap/bin:$PATH

script:
  - make setup-e2e-env
  - make vet
  - make test
  - make all
  - make static-tcpdump

before_deploy:
  - make package
  - git tag "$(cat VERSION)"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - ksniff.zip
  skip_cleanup: true
  on:
    tag: true
    branch: master