language: go

go:
  - "1.11.2"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev gcc

script:
  - make
  - make static-tcpdump

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - kubectl-sniff
    - kubectl-sniff-windows
    - kubectl-sniff-macos
    - static-tcpdump
  skip_cleanup: true
  on:
    all_branches: true